# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

# Explicitly disable only the rules we do not want.
linter:
  rules:
    # Some explanation why we don't want this lint
    sort_pub_dependencies: false